version: '3'

services:

  db:
    image: docker.io/postgres:15-alpine3.17
    environment:
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_USER: appuser
      POSTGRES_DB: auth
      PGDATA: var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - "$PWD/data:/var/lib/postgresql/data"

  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      REDIS_PASSWORD_FILE: /mnt/redis_password/redis_password
    ports:
      - 6379:6379
    volumes:
      - "$PWD/redis_password/redis_password:/mnt/redis_password/redis_password:ro"

  auth-server:
    image: docker.io/alexhokl/auth-server:dev
    environment:
      AUTH_DATABASE_CONNECTION_STRING: "host=db user=appuser password=Passw0rd dbname=auth port=5432 sslmode=disable"
      AUTH_REDIS_HOST: redis:6379
      AUTH_REDIS_PASSWORD: Passw0rd
      GIN_MODE: release
    ports:
      - 8080:8080
