package jwthelper_test

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"encoding/pem"
	"os"
	"path/filepath"
	"testing"

	"github.com/alexhokl/auth-server/jwthelper"
	"github.com/stretchr/testify/assert"
	"github.com/youmark/pkcs8"
)

// writeTestKeyFiles writes an encrypted ECDSA private key and its password to
// a temporary directory in the same format as the one generated by step in
// task gen-key.
func writeTestKeyFiles(t *testing.T, password string) (string, string, *ecdsa.PrivateKey) {
	t.Helper()

	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	assert.NoError(t, err)

	der, err := pkcs8.MarshalPrivateKey(key, []byte(password), nil)
	assert.NoError(t, err)

	keyBytes := pem.EncodeToMemory(&pem.Block{
		Type:  "ENCRYPTED PRIVATE KEY",
		Bytes: der,
	})

	dir := t.TempDir()
	keyPath := filepath.Join(dir, "ecdsa.key")
	passwordPath := filepath.Join(dir, "passphrase")

	assert.NoError(t, os.WriteFile(keyPath, keyBytes, 0o600))
	assert.NoError(t, os.WriteFile(passwordPath, []byte(password+"\n"), 0o600))

	return keyPath, passwordPath, key
}

func TestLoadEcdsaPrivateKey_LoadsKey(t *testing.T) {
	keyPath, passwordPath, expected := writeTestKeyFiles(t, "P@ssw0rd")

	key, err := jwthelper.LoadEcdsaPrivateKey(keyPath, passwordPath)

	assert.NoError(t, err)
	assert.NotNil(t, key)
	assert.Equal(t, 0, expected.D.Cmp(key.D))
	assert.Equal(t, 0, expected.X.Cmp(key.X))
	assert.Equal(t, 0, expected.Y.Cmp(key.Y))
	assert.Equal(t, elliptic.P256(), key.Curve)
}

func TestLoadEcdsaPrivateKey_WrongPassword(t *testing.T) {
	keyPath, _, _ := writeTestKeyFiles(t, "P@ssw0rd")

	otherPasswordPath := filepath.Join(t.TempDir(), "passphrase")
	assert.NoError(t, os.WriteFile(otherPasswordPath, []byte("not-the-password\n"), 0o600))

	key, err := jwthelper.LoadEcdsaPrivateKey(keyPath, otherPasswordPath)

	assert.Error(t, err)
	assert.Nil(t, key)
	assert.Contains(t, err.Error(), "unable to get ECDSA key")
}

func TestLoadEcdsaPrivateKey_NonExistentKeyFile(t *testing.T) {
	_, passwordPath, _ := writeTestKeyFiles(t, "P@ssw0rd")

	key, err := jwthelper.LoadEcdsaPrivateKey(
		filepath.Join(t.TempDir(), "missing.key"),
		passwordPath,
	)

	assert.Error(t, err)
	assert.Nil(t, key)
	assert.Contains(t, err.Error(), "unable to read private key")
}

func TestLoadEcdsaPrivateKey_NonExistentPasswordFile(t *testing.T) {
	keyPath, _, _ := writeTestKeyFiles(t, "P@ssw0rd")

	key, err := jwthelper.LoadEcdsaPrivateKey(
		keyPath,
		filepath.Join(t.TempDir(), "missing"),
	)

	assert.Error(t, err)
	assert.Nil(t, key)
	assert.Contains(t, err.Error(), "unable to read password")
}

func TestLoadEcdsaPrivateKey_MalformedKeyFile(t *testing.T) {
	_, passwordPath, _ := writeTestKeyFiles(t, "P@ssw0rd")

	keyPath := filepath.Join(t.TempDir(), "ecdsa.key")
	assert.NoError(t, os.WriteFile(keyPath, []byte("this is not a PEM block"), 0o600))

	key, err := jwthelper.LoadEcdsaPrivateKey(keyPath, passwordPath)

	assert.Error(t, err)
	assert.Nil(t, key)
	assert.Contains(t, err.Error(), "unable to get ECDSA key")
}
