definitions:
  api.AttestationObject:
    properties:
      attStmt:
        additionalProperties: true
        type: object
      authData:
        items:
          type: integer
        type: array
      fmt:
        type: string
    type: object
  api.AttestedCredentialData:
    properties:
      aaguid:
        items:
          type: integer
        type: array
      credential_id:
        items:
          type: integer
        type: array
      public_key:
        items:
          type: integer
        type: array
    type: object
  api.AuthenticatorAssertionResponse:
    properties:
      authenticatorData:
        items:
          type: integer
        type: array
      clientDataJSON:
        items:
          type: integer
        type: array
      signature:
        items:
          type: integer
        type: array
      userHandle:
        items:
          type: integer
        type: array
    type: object
  api.AuthenticatorAttestationResponse:
    properties:
      attestationObject:
        items:
          type: integer
        type: array
      clientDataJSON:
        items:
          type: integer
        type: array
      transports:
        items:
          type: string
        type: array
    type: object
  api.AuthenticatorData:
    properties:
      att_data:
        $ref: '#/definitions/api.AttestedCredentialData'
      ext_data:
        items:
          type: integer
        type: array
      flags:
        type: integer
      rpid:
        items:
          type: integer
        type: array
      sign_count:
        type: integer
    type: object
  api.ClientCreateRequest:
    properties:
      client_id:
        example: cli
        type: string
      client_secret:
        example: P@ssw0rd
        type: string
      redirect_uri:
        example: http://localhost:8080/callback
        type: string
      user_email:
        example: alex@test.com
        type: string
    required:
    - client_id
    - client_secret
    - redirect_uri
    - user_email
    type: object
  api.CollectedClientData:
    properties:
      challenge:
        type: string
      new_keys_may_be_added_here:
        type: string
      origin:
        type: string
      tokenBinding:
        $ref: '#/definitions/api.TokenBinding'
      type:
        type: string
    type: object
  api.CredentialAssertionResponse:
    properties:
      authenticatorAttachment:
        type: string
      clientExtensionResults:
        $ref: '#/definitions/api.DummyAuthenticationExtensionsClientOutputs'
      id:
        type: string
      rawId:
        items:
          type: integer
        type: array
      response:
        $ref: '#/definitions/api.AuthenticatorAssertionResponse'
      type:
        type: string
    type: object
  api.CredentialCreationResponse:
    properties:
      authenticatorAttachment:
        type: string
      clientExtensionResults:
        $ref: '#/definitions/api.DummyAuthenticationExtensionsClientOutputs'
      id:
        type: string
      rawId:
        items:
          type: integer
        type: array
      response:
        $ref: '#/definitions/api.AuthenticatorAttestationResponse'
      transports:
        items:
          type: string
        type: array
      type:
        type: string
    type: object
  api.DummyAuthenticationExtensionsClientOutputs:
    additionalProperties: true
    type: object
  api.DummyCredentialAssertionData:
    properties:
      authenticatorAttachment:
        type: string
      clientExtensionResults:
        $ref: '#/definitions/api.DummyAuthenticationExtensionsClientOutputs'
      id:
        type: string
      raw:
        $ref: '#/definitions/api.CredentialAssertionResponse'
      rawId:
        items:
          type: integer
        type: array
      response:
        $ref: '#/definitions/api.ParsedAssertionResponse'
      type:
        type: string
    type: object
  api.DummyCredentialCreationData:
    properties:
      authenticatorAttachment:
        type: string
      clientExtensionResults:
        $ref: '#/definitions/api.DummyAuthenticationExtensionsClientOutputs'
      id:
        type: string
      raw:
        $ref: '#/definitions/api.CredentialCreationResponse'
      rawId:
        items:
          type: integer
        type: array
      response:
        $ref: '#/definitions/api.DummyParsedAttestationResponse'
      type:
        type: string
    type: object
  api.DummyParsedAttestationResponse:
    properties:
      attestationObject:
        $ref: '#/definitions/api.AttestationObject'
      collectedClientData:
        $ref: '#/definitions/api.CollectedClientData'
      transports:
        items:
          type: string
        type: array
    type: object
  api.ParsedAssertionResponse:
    properties:
      authenticatorData:
        $ref: '#/definitions/api.AuthenticatorData'
      collectedClientData:
        $ref: '#/definitions/api.CollectedClientData'
      signature:
        items:
          type: integer
        type: array
      userHandle:
        items:
          type: integer
        type: array
    type: object
  api.TokenBinding:
    properties:
      id:
        type: string
      status:
        type: string
    type: object
  api.UserSignUpRequest:
    properties:
      email:
        example: alex@test.com
        type: string
      password:
        example: P@ssw0rd
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
  description: This API provides authentication and authorization services.
  title: Auth Server API
  version: 0.0.1
paths:
  /.well-known/openid-configuration:
    get:
      produces:
      - application/json
      responses: {}
      summary: OpenID configuration endpoint
      tags:
      - OpenID
  /.well-known/openid-configuration/jwks:
    get:
      produces:
      - application/json
      responses: {}
      summary: JSON web key set endpoint
      tags:
      - OpenID
  /.well-known/webfinger:
    get:
      produces:
      - application/jrd+json
      responses: {}
      summary: WebFinger endpoint
      tags:
      - OpenID
  /authorize:
    get:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: Response type (e.g. code)
        in: query
        name: response_type
        required: true
        type: string
      - description: Client ID
        in: query
        name: client_id
        required: true
        type: string
      - description: Redirect URI
        in: query
        name: redirect_uri
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Authorize and redirect to the redirect_uri
      tags:
      - OAuth
  /clients/:
    get:
      produces:
      - application/json
      responses: {}
      summary: Lists clients
      tags:
      - clients
    patch:
      consumes:
      - application/json
      description: Patches a OAuth client (not implemented yet)
      produces:
      - application/json
      responses: {}
      summary: Patches a client
      tags:
      - clients
    post:
      consumes:
      - application/json
      description: Adds a OAuth client
      parameters:
      - description: Client details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api.ClientCreateRequest'
      produces:
      - application/json
      responses: {}
      summary: Adds a client
      tags:
      - clients
  /fido/register:
    post:
      consumes:
      - application/json
      description: This completes the dance for registering a new credential
      parameters:
      - description: Credential creation request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api.DummyCredentialCreationData'
      produces:
      - application/json
      responses: {}
      summary: Verifies and creates a new credential
      tags:
      - user
  /fido/register/challenge:
    post:
      description: This starts the dance for registering a new credential
      produces:
      - application/json
      responses: {}
      summary: Serves a challenge for registering a new credential
      tags:
      - user
  /fido/signin:
    post:
      consumes:
      - application/json
      description: This completes the dance for sign in
      parameters:
      - description: Credential assertion request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api.DummyCredentialAssertionData'
      produces:
      - application/json
      responses: {}
      summary: Verifies user credential and sign in
      tags:
      - user
  /fido/signin/challenge:
    post:
      description: This starts the dance for sign in
      produces:
      - application/json
      responses: {}
      summary: Serves a challenge for starting a login dance
      tags:
      - user
  /signin:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - example: alex@test.com
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Starts a sign in session with a user
      tags:
      - user
  /signin/challenge:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - example: P@ssw0rd
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Signs in a user with a password
      tags:
      - user
  /signout:
    post:
      description: Signs out a user and deletes its email from session. Note that
        the session cookie would not be deleted.
      produces:
      - application/json
      responses: {}
      summary: Signs out a user
      tags:
      - user
  /signup:
    post:
      consumes:
      - application/json
      description: Creates a new user but it does not verify the email address yet
      parameters:
      - description: User sign up request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api.UserSignUpRequest'
      produces:
      - application/json
      responses: {}
      summary: Creates a new user
      tags:
      - user
  /token:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - example: cli
        in: formData
        name: client_id
        required: true
        type: string
      - example: P@ssw0rd
        in: formData
        name: client_secret
        required: true
        type: string
      - example: code
        in: formData
        name: code
        required: true
        type: string
      - example: authorization_code
        in: formData
        name: grant_type
        required: true
        type: string
      - example: http://localhost:8088
        in: formData
        name: redirect_uri
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Issues a token
      tags:
      - OAuth
swagger: "2.0"
